### ISSUE TITLE
[feature request] GitHub Actions support?

### ISSUE THREAD

**Issue by JounQin** [continuousauth/web#3]
Thanks for your great job.

**Comment by MarshallOfSound** [comment]
Now that their is a GitHub Actions API this might be possible, I can look into it at some point 👍

**Comment by MarshallOfSound** [comment]
Blocked by / depends on the resolution to https://github.com/actions/runner/issues/324

**Comment by mmarchini** [comment]
@MarshallOfSound why CFA needs to check logs for Action support to work? Are there any validations made using logs?
