### ISSUE TITLE
Add project failed with error "Current user is not an admin of the target repository"

### ISSUE THREAD

**Issue by jkzing** [continuousauth/web#88]
I was trying to add a project to continuousauth.dev but got an error. The error looks like:

![CleanShot 2024-12-24 at 13 57 29@2x](https://github.com/user-attachments/assets/fb3da8eb-5533-411a-b917-067bb1c91e15)

I'm pretty sure the GitHub account has the admin access to the repo. Actually I've tried the GitHub API continuousauth use (`/repositories/:repo_id/collaborators/:username/permission`), it shows the permission is "admin" as expected.

Not sure which part I was doing wrong, or maybe it's a bug of continuousauth?

![CleanShot 2024-12-24 at 14 01 27@2x](https://github.com/user-attachments/assets/e4be420c-fb07-434b-ba83-0333de6dffdd)

**Comment by MarshallOfSound** [comment]
Hm, the setup flow might not have guided you to installing the GitHub App. The app is what checks permission rather than the oauth token obtained during sign in.

I can send you a direct link for app install

**Comment by MarshallOfSound** [comment]
@jkzing This is the GitHub App that powers things now --> https://github.com/apps/continuous-auth

We switched a while back from a stored oauth token to a GitHub App for better permission scoping.

**Comment by jkzing** [comment]
@MarshallOfSound I see, will add this app and try again.  Thanks for your help. ;)

**Comment by jkzing** [comment]
It works! Closing this issue and thanks again!

**Comment by MarshallOfSound** [comment]
No problem, happy to help you get this going if it means securing the npm ecosystem more
